# Generated by Django 4.0.3 on 2022-12-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_reg', '0002_phoneuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverifiaction',
            name='date',
            field=models.CharField(default='2022-12-23', max_length=10),
        ),
        migrations.AddField(
            model_name='phoneuser',
            name='date',
            field=models.CharField(default='2022-12-23', max_length=10),
        ),
    ]
