# Generated by Django 4.0.3 on 2022-08-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=2322, null=True)),
                ('description', models.CharField(blank=True, max_length=2322, null=True)),
                ('profile', models.CharField(blank=True, max_length=2322, null=True)),
                ('role', models.CharField(blank=True, max_length=2322, null=True)),
                ('rating', models.CharField(blank=True, max_length=2322, null=True)),
            ],
        ),
    ]
