# Generated by Django 4.0.3 on 2022-08-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_reviewsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsection',
            name='image',
            field=models.CharField(blank=True, max_length=23222222222222, null=True),
        ),
    ]
