# Generated by Django 4.0.3 on 2022-10-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryDaa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=121111, null=True)),
            ],
        ),
    ]
