# Generated by Django 4.0.3 on 2022-12-23 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_jobapply_jobsrequired_telemetrydaa_teleid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsection',
            name='created_at',
            field=models.CharField(default=datetime.date(2012, 1, 11), max_length=150),
        ),
    ]
