# Generated by Django 4.0.3 on 2022-12-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_reviewsection_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapply',
            name='created_at',
            field=models.CharField(default='2022-12-23', max_length=150),
        ),
        migrations.AddField(
            model_name='jobsrequired',
            name='created_at',
            field=models.CharField(default='2022-12-23', max_length=150),
        ),
        migrations.AddField(
            model_name='telemetrydaa',
            name='date',
            field=models.CharField(default='2022-12-23', max_length=10),
        ),
        migrations.AlterField(
            model_name='reviewsection',
            name='created_at',
            field=models.CharField(default='2022-12-23', max_length=150),
        ),
    ]
