# Generated by Django 4.0.3 on 2022-06-09 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adsapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adsCommentDate', models.CharField(default='none', max_length=121)),
                ('comment', models.TextField()),
                ('ads', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='adsapi.product')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
