# Generated by Django 4.0.3 on 2022-06-09 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adsapi', '0002_adscomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdsComment',
        ),
    ]
