# Generated by Django 4.0.3 on 2022-06-16 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adsapi', '0003_delete_adscomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='adsmangeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('adsUserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_secondary_manual_roats', to=settings.AUTH_USER_MODEL)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_primary_manual_roats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
