# Generated by Django 4.0.3 on 2022-06-16 08:15

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('adsapi', '0004_adsmangeme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adsmangeme',
            name='message',
            field=picklefield.fields.PickledObjectField(editable=False),
        ),
    ]
