# Generated by Django 4.0.3 on 2022-07-26 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adsapi', '0005_alter_adsmangeme_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateEnquery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=232)),
                ('lastName', models.CharField(max_length=232)),
                ('email', models.CharField(max_length=343)),
                ('zip_code', models.CharField(max_length=232)),
            ],
        ),
        migrations.AddField(
            model_name='adsmangeme',
            name='connectMember',
            field=models.CharField(default='srishtisrija@gmail.com', max_length=223232),
        ),
        migrations.AddField(
            model_name='product',
            name='lati',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='long',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='subCategoryType',
            field=models.CharField(default='null', max_length=3232),
        ),
        migrations.AddField(
            model_name='product',
            name='subCategoryValue',
            field=models.CharField(default='null', max_length=3232),
        ),
        migrations.AddField(
            model_name='product',
            name='viewsproduct',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='adsmangeme',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.CreateModel(
            name='ReportAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(max_length=23222)),
                ('ads', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adsapi.product')),
            ],
        ),
        migrations.CreateModel(
            name='ImageAdsModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upload/images')),
                ('ads', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adsapi.product')),
            ],
        ),
        migrations.CreateModel(
            name='AdsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=23222)),
                ('datetimeValue', models.CharField(max_length=232)),
                ('message', models.CharField(max_length=23222)),
                ('ads', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adsapi.product')),
            ],
        ),
        migrations.CreateModel(
            name='AdsAdressLatLon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.IntegerField()),
                ('lon', models.IntegerField()),
                ('ads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adsapi.product')),
            ],
        ),
    ]
