# Generated by Django 4.0.3 on 2022-07-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsapi', '0006_realestateenquery_adsmangeme_connectmember_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, max_length=150222, null=True),
        ),
    ]
