# Generated by Django 4.0.3 on 2022-07-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsapi', '0008_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phoneNumber',
            field=models.CharField(blank=True, default='null', max_length=112, null=True),
        ),
    ]
