# Generated by Django 4.0.3 on 2022-07-28 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adsapi', '0009_product_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='phoneNumber',
        ),
    ]
