# Generated by Django 4.0.3 on 2022-07-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsapi', '0010_remove_product_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phoneNumber',
            field=models.CharField(blank=True, default='null', max_length=112, null=True),
        ),
    ]
