# Generated by Django 4.0.3 on 2022-07-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsapi', '0011_product_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageadsmodels',
            name='image',
            field=models.CharField(blank=True, max_length=1502222222222222, null=True),
        ),
    ]
