# Generated by Django 4.0.3 on 2022-08-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsapi', '0015_product_apartmenttype_product_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ApartMentType',
            field=models.CharField(blank=True, default='NoData', max_length=112111, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Availability',
            field=models.CharField(blank=True, default='NoData', max_length=112111, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='BuildUpArea',
            field=models.CharField(blank=True, default='NoData', max_length=112111, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Flor',
            field=models.CharField(blank=True, default='NoData', max_length=112111, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='FurnishedType',
            field=models.CharField(blank=True, default='NoData', max_length=112111, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Garden',
            field=models.CharField(blank=True, default='NoData', max_length=112111, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Gym',
            field=models.CharField(blank=True, default='NoData', max_length=112111, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Lift',
            field=models.CharField(blank=True, default='NoData', max_length=112111, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Parking',
            field=models.CharField(blank=True, default='NoData', max_length=112111, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Pool',
            field=models.CharField(blank=True, default='NoData', max_length=112111, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='PowerBackup',
            field=models.CharField(blank=True, default='NoData', max_length=112111, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Property',
            field=models.CharField(blank=True, default='NoData', max_length=112111, null=True),
        ),
    ]
