# Generated by Django 4.0.3 on 2022-08-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsapi', '0016_alter_product_apartmenttype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/images'),
        ),
    ]
