# Generated by Django 4.0.3 on 2022-08-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsapi', '0019_product_plancategory_product_ads_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='adsLeft',
            field=models.CharField(max_length=1211, null=True),
        ),
    ]
