# Generated by Django 4.0.3 on 2022-08-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsapi', '0021_adminauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminauth',
            name='name',
            field=models.CharField(max_length=2322, null=True),
        ),
    ]
