# Generated by Django 4.0.3 on 2022-09-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsapi', '0022_adminauth_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.CharField(default='null', max_length=150),
        ),
    ]
