# Generated by Django 4.0.3 on 2022-09-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsapi', '0023_alter_product_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colorCheck',
            field=models.CharField(max_length=2322, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='end',
            field=models.CharField(max_length=2322, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='oldPetsCheck',
            field=models.CharField(max_length=2322, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sizeCheck',
            field=models.CharField(max_length=2322, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='start',
            field=models.CharField(max_length=2322, null=True),
        ),
    ]
