# Generated by Django 4.0.3 on 2022-09-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsapi', '0024_product_colorcheck_product_end_product_oldpetscheck_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='college',
            field=models.CharField(max_length=2322, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='engine',
            field=models.CharField(max_length=2322, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='school',
            field=models.CharField(max_length=2322, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='year',
            field=models.CharField(max_length=2322, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=2322, null=True),
        ),
    ]
