# Generated by Django 4.0.3 on 2022-09-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsapi', '0025_product_college_product_engine_product_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kmdriven',
            field=models.CharField(max_length=2322, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='registrationYear',
            field=models.CharField(max_length=2322, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='setkmDriven',
            field=models.CharField(max_length=2322, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='setregistrationYear',
            field=models.CharField(max_length=2322, null=True),
        ),
    ]
