# Generated by Django 4.0.3 on 2022-10-09 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paymentapi', '__first__'),
        ('adsapi', '0027_product_extrafield'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetailsValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderValue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paymentapi.order')),
                ('PlanValue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adsapi.pricing')),
                ('UserValue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
