# Generated by Django 4.0.3 on 2022-12-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsapi', '0030_wishlistdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='extraField',
        ),
        migrations.AddField(
            model_name='product',
            name='DaysLimit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='adsType',
            field=models.CharField(max_length=2322, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='expiry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='plan',
            field=models.CharField(max_length=2322, null=True),
        ),
    ]
