# Generated by Django 4.0.3 on 2022-12-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsapi', '0032_product_extrafield_alter_product_adstype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='adsLeft',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='ads_limit',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='ads_timing',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='featured_ads',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='support',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='top_listing',
        ),
        migrations.AddField(
            model_name='pricing',
            name='chatSupport',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='pricing',
            name='days',
            field=models.CharField(max_length=2322, null=True),
        ),
        migrations.AddField(
            model_name='pricing',
            name='dedicatedRm',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='pricing',
            name='featured',
            field=models.CharField(max_length=2322, null=True),
        ),
        migrations.AddField(
            model_name='pricing',
            name='hol9Website',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='pricing',
            name='regulars',
            field=models.CharField(max_length=2322, null=True),
        ),
        migrations.AddField(
            model_name='pricing',
            name='response',
            field=models.CharField(max_length=1211, null=True),
        ),
        migrations.AddField(
            model_name='pricing',
            name='teleSupport',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='pricing',
            name='topAds',
            field=models.CharField(max_length=2322, null=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='category',
            field=models.CharField(max_length=2322, null=True),
        ),
    ]
