# Generated by Django 4.0.3 on 2022-12-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsapi', '0033_remove_pricing_adsleft_remove_pricing_ads_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='chatSupport',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='dedicatedRm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='hol9Website',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='teleSupport',
            field=models.BooleanField(default=False),
        ),
    ]
