# Generated by Django 4.0.3 on 2022-12-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsapi', '0038_alter_adsmangeme_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
