# Generated by Django 4.0.3 on 2022-07-26 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogsapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='category',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=23222)),
                ('datetimeValue', models.CharField(max_length=232)),
                ('message', models.CharField(max_length=23222)),
                ('ads', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogsapi.blogs')),
            ],
        ),
    ]
