# Generated by Django 4.0.3 on 2022-08-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsapi', '0002_blogs_category_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='author',
            field=models.CharField(default='null', max_length=150),
        ),
        migrations.AddField(
            model_name='blogs',
            name='imagesecond',
            field=models.ImageField(default='null', upload_to='upload/images'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='published_time',
            field=models.CharField(default='null', max_length=150),
        ),
        migrations.AddField(
            model_name='blogs',
            name='subtitle',
            field=models.CharField(default='null', max_length=150),
        ),
    ]
