# Generated by Django 4.0.3 on 2022-12-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsapi', '0003_blogs_author_blogs_imagesecond_blogs_published_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='published_time',
            field=models.CharField(default='2022-12-23', max_length=232),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='published_time',
            field=models.CharField(default='2022-12-23', max_length=150),
        ),
    ]
