# Generated by Django 4.0.3 on 2022-06-10 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogscommentbox', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogscomment',
            old_name='ads',
            new_name='blogs',
        ),
    ]
