# Generated by Django 4.0.3 on 2022-06-10 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogscommentbox', '0002_rename_ads_blogscomment_blogs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogscomment',
            old_name='content',
            new_name='comment',
        ),
    ]
