# Generated by Django 4.0.3 on 2022-12-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapi', '0002_alter_order_order_datetele'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transationidone',
            name='date_created',
            field=models.CharField(default='2022-12-23', max_length=550),
        ),
    ]
